//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelRefunds.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TravelRefunds.Resources.Localization.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m Daniele Tentoni, enthusiast with Xamarin.Forms doing this application as a curriculum app to show what things I can do with this awesome framework..
        /// </summary>
        public static string AboutPresentationText {
            get {
                return ResourceManager.GetString("AboutPresentationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curriculum Application.
        /// </summary>
        public static string AboutPresentationTitle {
            get {
                return ResourceManager.GetString("AboutPresentationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awesome icons from Font Awesome..
        /// </summary>
        public static string AwesomeIcons {
            get {
                return ResourceManager.GetString("AwesomeIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Location.
        /// </summary>
        public static string CalculateFromLocation {
            get {
                return ResourceManager.GetString("CalculateFromLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Location.
        /// </summary>
        public static string CalculateToLocation {
            get {
                return ResourceManager.GetString("CalculateToLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator.
        /// </summary>
        public static string Calculator {
            get {
                return ResourceManager.GetString("Calculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fancy animations as Splashscreens and Calculator Job Done..
        /// </summary>
        public static string LottieDesc {
            get {
                return ResourceManager.GetString("LottieDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store recently calculated refunds. You can retreive them from History Page..
        /// </summary>
        public static string MonkeyBarrelsDesc {
            get {
                return ResourceManager.GetString("MonkeyBarrelsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal a Bug.
        /// </summary>
        public static string SignalABug {
            get {
                return ResourceManager.GetString("SignalABug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for travel distance to Bing services..
        /// </summary>
        public static string TravelApiDesc {
            get {
                return ResourceManager.GetString("TravelApiDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What I&apos;ve implemented in this application:.
        /// </summary>
        public static string WhatImplemented {
            get {
                return ResourceManager.GetString("WhatImplemented", resourceCulture);
            }
        }
    }
}
